import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppProvider from "@/hooks";
import clsx from "clsx";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CatApi Instance | Maycom Will",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppProvider>
      <html lang="pt-BR">
        <body className={clsx("bg-slate-900 text-zinc-100", inter.className)}>
          <Header />
          {children}
        </body>
      </html>
    </AppProvider>
  );
}
